#!/usr/bin/env python

from helpers import git
import argparse
import webbrowser

URL_TEMPLATE = "https://circleci.com/{}/{}/{}"


def main(provider, repo, identifier):
    if identifier:
        try:
            path = str(int(identifier))
        except ValueError:
            path = "tree/{}".format(identifier)
    else:
        path = ""

    provder_argument = "gh" if provider == "github" else ""
    url = URL_TEMPLATE.format(provder_argument, repo, path)
    webbrowser.open_new_tab(url)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--provider", default="github")
    parser.add_argument("-r", "--repo", default=git.current_repo_path())
    parser.add_argument("IDENTIFIER",
                        help="The branch or build number to open", nargs="?")

    arguments = parser.parse_args()
    if arguments.repo is None:
        parser.error("Repo is required")

    main(arguments.provider, arguments.repo, arguments.IDENTIFIER)
