#!/bin/sh

set -e

if [[ "$#" -eq "0" ]]; then
  echo "Usage: circle [COMMAND] [ARGUMENTS]"
  exit 0
fi

cmd="circle-$1"
shift

if hash $cmd 2>/dev/null; then
  eval "$cmd $@"
else
  echo "'$cmd' was not found in your \$PATH"
  exit 1
fi
