#!/usr/bin/env python

from helpers import credentials
from helpers import git
import argparse
import requests
import signal
import sys

URL_TEMPLATE = "https://circleci.com/api/v1.1/project/{}/{}/build-cache"


def signal_handle(sig, frame):
    sys.exit(0)


def main(provider, repo):
    url = URL_TEMPLATE.format(provider, repo)
    password = credentials.credentials()
    params = {"circle-token": password}
    headers = {"Content-Type": "application/json"}
    response = requests.delete(url, params=params, headers=headers)
    if response.status_code != 200:
        print("Failed to delete build cache: {}".format(response.json()))
        sys.exit(1)


signal.signal(signal.SIGINT, signal_handle)
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--provider", default="github")
    parser.add_argument("-r", "--repo", default=git.current_repo_path())
    arguments = parser.parse_args()

    if arguments.repo is None:
        parser.error("Repo is required\n\n{}".format(parser.format_help()))

    main(arguments.provider, arguments.repo)
