#!/usr/bin/env python

from __future__ import print_function
from helpers import credentials
from helpers import formatter
from helpers import git
import argparse
import json
import requests
import signal
import sys

URL_TEMPLATE = "https://circleci.com/api/v1.1/project/{}/{}/{}"


def signal_handle(sig, frame):
    sys.exit(0)


def _extract_custom_fields(build, fields):
    output = []
    for field in fields:
        parts = field.split(".")
        obj = build
        for part in parts:
            try:
                obj = obj[part]
            except (KeyError, TypeError):
                pretty_string = json.dumps(build, indent=4)
                print("Failed to access '{}' in\n{}"
                      .format(field, pretty_string), file=sys.stderr)
                sys.exit(1)
        if obj is not None:
            output.append(obj)
    return output


def _format_build(build, fields, include_branch):
    output = []
    output.append(build["build_num"])
    output.append(build["status"])
    output += _extract_custom_fields(build, fields)
    if include_branch:
        output.append(build["branch"])
    output.append(build["author_name"])
    return output


def main(provider, repo, fields, branch):
    branch_argument = "tree/{}".format(branch) if branch else ""
    url = URL_TEMPLATE.format(provider, repo, branch_argument)
    password = credentials.credentials()
    params = {"circle-token": password}
    response = requests.get(url, params=params)

    if response.status_code != 200:
        print(response.json(), file=sys.stderr)
        sys.exit(1)

    rows = [_format_build(build, fields, branch is None)
            for build in response.json()]
    formatter.output_rows(rows)

signal.signal(signal.SIGINT, signal_handle)
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-b", "--branch")
    parser.add_argument("-f", "--fields", nargs="+")
    parser.add_argument("-p", "--provider", default="github")
    parser.add_argument("-r", "--repo", default=git.current_repo_path())

    arguments = parser.parse_args()

    if arguments.repo is None:
        parser.error("Repo is required\n\n{}".format(parser.format_help()))

    main(arguments.provider, arguments.repo, arguments.fields or [],
         arguments.branch)
