#!/usr/bin/env python

from __future__ import print_function
from helpers import circle
from helpers import formatter
from helpers import git
import argparse
import json
import signal
import sys


def signal_handle(sig, frame):
    sys.exit(0)


def main(provider, repo, build_num):
    print(json.dumps(circle.get_build(provider, repo, build_num), indent=4))


signal.signal(signal.SIGINT, signal_handle)
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--provider", default="github")
    parser.add_argument("-r", "--repo", default=git.current_repo_path())
    parser.add_argument("BUILD_NUM")

    arguments = parser.parse_args()

    if arguments.repo is None:
        parser.error("Repo is required")

    main(arguments.provider, arguments.repo, arguments.BUILD_NUM)
