#!/usr/bin/env python

from helpers import git
import argparse
import signal
import sys
import webbrowser

URL_TEMPLATE = "https://circleci.com/{}/{}/{}"


def signal_handle(sig, frame):
    sys.exit(0)


def main(build, branch, _, repo):
    last_part = build if build else "tree/{}".format(branch)
    url = URL_TEMPLATE.format("gh", repo, last_part)
    webbrowser.open_new_tab(url)


signal.signal(signal.SIGINT, signal_handle)
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--provider", default="github")
    parser.add_argument("-r", "--repo", default=git.current_repo_path())

    group = parser.add_mutually_exclusive_group()
    group.add_argument("-b", "--branch", help="The branch build page to open")
    group.add_argument("-n", "--number", help="The CircleCI build number")

    arguments = parser.parse_args()

    if arguments.repo is None:
        parser.error("Repo is required\n\n{}".format(parser.format_help()))

    if arguments.branch is None and arguments.number is None:
        parser.error("Branch or build number is required\n\n{}"
                     .format(parser.format_help()))

    main(arguments.number, arguments.branch, arguments.provider,
         arguments.repo)
